let cookies=document.cookie;const notices=document.querySelectorAll(".video__notice");function deactivateCookies(){document.cookie="ytPreference=; expires=Thu, 01 Jan 1970 00:00:00 UTC;",deactivateVideos()}function activateVideos(){let e=document.querySelectorAll('.video__iframe[data-src*="youtube-nocookie.com"]');e.forEach(e=>{e.src=e.dataset.src,e.classList.remove("yt_hidden")}),notices.forEach(e=>{e.classList.add("notice_hidden")})}function deactivateVideos(){let e=document.querySelectorAll('.video__iframe[src*="youtube-nocookie.com"]');e.forEach(e=>{e.removeAttribute("src"),e.classList.add("yt_hidden")}),notices.forEach(e=>{e.classList.remove("notice_hidden")})}-1!==cookies.indexOf("ytPreference=allow")&&activateVideos(),notices.forEach(e=>{e.addEventListener("submit",e=>{activateVideos(),e.preventDefault(),document.cookie="ytPreference=allow"})});const hamburger=document.querySelector(".hamburger"),mainNav=document.querySelector(".main_nav"),navLink=document.querySelectorAll(".nav_link"),navLink2=document.querySelectorAll(".paragon_logo"),gamesMenu=document.getElementById("nav_item3"),dropdownMenu=document.getElementById("games_hover");function mobileMenu(){hamburger.classList.toggle("active"),mainNav.classList.toggle("active"),ariaExpUpdater()}function closeMenu(){hamburger.classList.remove("active"),mainNav.classList.remove("active"),ariaExpUpdater()}hamburger.addEventListener("click",mobileMenu),navLink.forEach(e=>e.addEventListener("click",closeMenu)),navLink2.forEach(e=>e.addEventListener("click",closeMenu)),window.addEventListener("click",function(e){!0!=e.target.className.includes("nav_element")&&closeMenu()}),window.addEventListener("keydown",function(e){"Escape"===e.key&&hamburger.classList.contains("active")&&(this.document.getElementById("menu-icon").focus(),closeMenu())});let hamExpValue="false";function ariaExpUpdater(){hamExpValue=!0!=hamburger.classList.contains("active")?"false":"true",document.getElementById("menu-icon").setAttribute("aria-expanded",hamExpValue)}function ariaLabelUpdater(){let e=document.getElementById("menu-icon").getAttribute("aria-label");e=hamburger.classList.contains("active")?"open-menu":"close-menu",document.getElementById("menu-icon").setAttribute("aria-label",e)}const gamesSubMenu=document.querySelector(".games_hover");function gamesToggleActive(){gamesSubMenu.classList.toggle("active"),gamesMenu.classList.toggle("active"),gamesSubMenu.classList.contains("active")?(gamesSubMenu.setAttribute("aria-expanded","true"),gamesSubMenu.setAttribute("aria-label","Close Games Submenu")):(gamesSubMenu.setAttribute("aria-expanded","false"),gamesSubMenu.setAttribute("aria-label","Open Games Submenu"))}window.addEventListener("click",function(e){e.target.className.includes("games_menu")||(gamesSubMenu.classList.remove("active"),gamesMenu.classList.remove("active"),gamesSubMenu.setAttribute("aria-expanded","false"),gamesSubMenu.setAttribute("aria-label","Open Games Submenu"))});

(function() {
    let co=document.createElement("script");
    co.type="text/javascript";
    co.async=true;
    co.src="https://xola.com/checkout.js";
    let s=document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(co, s);
})();

            